"""change enum

Revision ID: 11449414905c
Revises: 6d0146d6d35f
Create Date: 2024-05-21 08:42:26.659229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '11449414905c'
down_revision: Union[str, None] = '6d0146d6d35f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('llmbackend', 'model_vendor',
               existing_type=mysql.ENUM('OPENAI', 'CLAUDE'),
               type_=sa.Enum('OPENAI', 'ANTHROPIC', name='modelvendor'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('llmbackend', 'model_vendor',
               existing_type=sa.Enum('OPENAI', 'ANTHROPIC', name='modelvendor'),
               type_=mysql.ENUM('OPENAI', 'CLAUDE'),
               existing_nullable=False)
    # ### end Alembic commands ###
