"""change template to text

Revision ID: 4c884b5f785a
Revises: 3f7dbcad2fd3
Create Date: 2024-05-09 19:17:30.406495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4c884b5f785a'
down_revision: Union[str, None] = '3f7dbcad2fd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prompt', 'template',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prompt', 'template',
               existing_type=sa.TEXT(),
               type_=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
